name: wemanity_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1  
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  vrouter: ^1.2.1
  websafe_svg: ^2.0.0
  material: ^1.0.0+2
  retrofit: '>=3.0.0 <4.0.0'
  logger: any


dev_dependencies:
  retrofit_generator: '>=3.0.0 <5.0.0'
  json_serializable: '>4.4.0'
  bloc_test: ^9.0.2
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.0+1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  lint: ^1.7.2
  mockito: ^5.0.10


flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/wemanity.png"

flutter_native_splash:
  color: "#78BE20"
  image: "assets/images/wemanity.png"
  android: true
  ios: false
  web: true
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/





